### ISSUE TITLE
doesnt work with ng-model-options

### ISSUE THREAD

**Issue by apansky** [jacek-pulit/angular-elastic-input#11]
Hey,

thanx for great directive. However, i would need it to work with ng-model-options, right now, it updates width each time the model updates, in my scenario i would like to work same way but with ng-model-options="{updateOn: 'blur'}", could you fix it maybe or should i do pull request?

Thanx again !

**Comment by jacek-pulit** [comment]
Hey, ngModelOptions was introduced in Angular 1.3.x, so maybe this is the reason why it does not work for you. I checked it with new angular - it works like you want.
