### ISSUE TITLE
Does not support number type inputs

### ISSUE THREAD

**Issue by jpuffer** [jacek-pulit/angular-elastic-input#22]
In the case of an input with type="number", the calculated size is too small and the number cuts off, because the browser creates a spinner pseudoelement on the right side of the input.  In chrome, the space it takes is about 13-19 pixels wide (depending on the font size of the input.)

![screen shot 2016-09-15 at 5 30 09 pm](https://cloud.githubusercontent.com/assets/2469870/18571786/1e8af890-7b6a-11e6-8898-b195947fcd3e.png)
![screen shot 2016-09-15 at 5 31 06 pm](https://cloud.githubusercontent.com/assets/2469870/18571797/3824d91a-7b6a-11e6-8680-337ebe13c034.png)

**Comment by jacek-pulit** [comment]
Hey Jake,
There is an undocumented option `pu-elastic-input-width-delta="15px"` that you can set additional pixels for your input. 
Alternatively you can hide the spinners https://css-tricks.com/snippets/css/turn-off-number-input-spinners/
I guess there is no way to calculate width of these spinners, but I will look for it later
Thank you for pointing this out

**Comment by jpuffer** [comment]
Rad! Thanks for pointing that out.  I'll totally use those free pixels on my number inputs.

**Comment by jpuffer** [comment]
Works like a charm. 
![image](https://cloud.githubusercontent.com/assets/2469870/18601942/c22da6e0-7c1a-11e6-8f33-4fa590e7460a.png)

**Comment by jacek-pulit** [comment]
I'm glad you like it.
Cheers!
