### ISSUE TITLE
Not detecting spaces with default attributes

### ISSUE THREAD

**Issue by oleduc** [jacek-pulit/angular-elastic-input#4]
Hello,

When entering spaces, the input will not stretch. This is due to angularJS now trimming trailing spaces by default, so they aren't added to the model.

Simply adding ng-trim="false" to the input does the trick. However, it would be good to either do it automatically or add it to the documentation of your directive.

Thank you.

**Comment by Vladimir-Purple** [comment]
Thanks for the solution.
